package de.uol.swp.client.auth;

import de.uol.swp.client.AbstractPresenter;
import de.uol.swp.client.register.event.ShowRegistrationViewEvent;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;

/**
 * Manages the login window.
 *
 * @see de.uol.swp.client.AbstractPresenter
 */
@SuppressWarnings("UnstableApiUsage")
public class LoginPresenter extends AbstractPresenter {

  public static final String FXML = "/fxml/view/LoginView.fxml";

  private static final ShowRegistrationViewEvent showRegViewMessage =
      new ShowRegistrationViewEvent();

  @FXML private PasswordField passwordField;
  @FXML private TextField loginField;

  /** Default Constructor. */
  public LoginPresenter() {
    // needed for javafx
  }

  /**
   * Method called when the login button is pressed.
   *
   * <p>This Method is called when the login button is pressed. It takes the text entered in the
   * login and password field and gives the user service a request to log in the user specified by
   * those fields.
   *
   * @param event The ActionEvent generated by pressing the login button
   * @see de.uol.swp.client.user.UserService
   */
  @FXML
  private void onLoginButtonPressed(ActionEvent event) {
    userService.login(loginField.getText(), passwordField.getText());
    passwordField.clear();
    event.consume();
  }

  /**
   * Method called when the register button is pressed.
   *
   * <p>This Method is called when the register button is pressed. It posts an instance of the
   * ShowRegistrationViewEvent to the EventBus the SceneManager is subscribed to.
   *
   * @param event The ActionEvent generated by pressing the register button
   * @see de.uol.swp.client.register.event.ShowRegistrationViewEvent
   * @see de.uol.swp.client.SceneManager
   */
  @FXML
  private void onRegisterButtonPressed(ActionEvent event) {
    eventBus.post(showRegViewMessage);
    event.consume();
  }
}
